spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-test-db?serverTimezone=UTC&characterEncoding=UTF-8
    username: my-test-db
    password: my-test-db
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
