spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my-test-db
    username: my-test-db
    password: my-test-db
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
